import {
  ElButton,
  ElForm,
  ElFormItem,
  ElInput,
  ElMessage,
  ElContainer,
  ElHeader,
  ElAside,
  ElMain,
  ElMenu,
  ElSubmenu,
  ElMenuItem,
  ElIcon,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElCard,
  ElRow,
  ElCol,
  ElTable,
  ElTableColumn,
  ElSwitch,
  ElPagination,
  ElDialog,
  ElMessageBox,
  ElTag,
  ElTree,
  ElAlert,
  ElSteps,
  ElStep,
  ElTabs,
  ElTabPane,
  ElCascader,
  ElCheckboxGroup,
  ElCheckbox,
  ElUpload
} from 'element-plus'

export default (app) => {
  app.use(ElButton)
  app.use(ElForm)
  app.use(ElInput)
  app.use(ElFormItem)
  app.use(ElMessage)
  app.use(ElContainer)
  app.use(ElHeader)
  app.use(ElAside)
  app.use(ElMain)
  app.use(ElMenu)
  app.use(ElSubmenu)
  app.use(ElMenuItem)
  app.use(ElIcon)
  app.use(ElBreadcrumb)
  app.use(ElBreadcrumbItem)
  app.use(ElCard)
  app.use(ElRow)
  app.use(ElCol)
  app.use(ElTable)
  app.use(ElTableColumn)
  app.use(ElSwitch)
  app.use(ElPagination)
  app.use(ElDialog)
  app.use(ElMessageBox)
  app.use(ElTag)
  app.use(ElTree)
  app.use(ElAlert)
  app.use(ElSteps)
  app.use(ElStep)
  app.use(ElTabs)
  app.use(ElTabPane)
  app.use(ElCascader)
  app.use(ElCheckboxGroup)
  app.use(ElCheckbox)
  app.use(ElUpload)
}
